### ISSUE TITLE
Create Theta Tier Buildings

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/Acquistion-of-Technology#13]
# Description
Add Theta Tier buildings to the mod to be used when the Secrets of the Shroud mod is installed and active.

## TODO

- [x] Create the Building Icon art. 
![theta_buildings1](https://user-images.githubusercontent.com/19975052/183686357-3b0cb1df-129f-497b-8b37-1ea4dbb781d1.png)
- [x] Create the Technology icon art
![theta_building_techs1](https://user-images.githubusercontent.com/19975052/183686348-d7ac3b0b-3f76-47ad-849c-424905de6e5b.png)
- [x] Implement the code for the Theta Buildings
- [x] Implement the jobs for the workeable buildings.
- [x] Implement the code for the Theta building technologies.

**Comment by Fragjacker** [comment]
This issue is fully implemented.
