### ISSUE TITLE
Create Theta Tier Star Imploder

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/Acquistion-of-Technology#14]
# Description
Phanon already uses the Star Imploder tech and Theta should, as its logical successor tier, build upon this content. The idea is to make the existing Phanon Megastructures and infrastructure evolve both visually and gameplay wise into their Theta pendant.

## TODO

- [x] Create a new mesh for the theta star imploder, which uses the fallen empire aesthetics. (Organic and round)
- [x] Texture the mesh.
- [x] Finish the mesh in blender and export it.
- Implement the megastructure code in-game
  - [x] Create new VFX to match the purple theta tier aesthetics. 
  - [ ] Add code for the technology.
  - [ ] Add icon for technology.
  - [ ] Add localisation.
  - [ ] Create new events when the building is completed.
  - [ ] Create new SFX to make it more interesting. (Optional)

**Comment by Fragjacker** [comment]
It's currently in the process of being textured.

**Comment by Fragjacker** [comment]
Texturing is finished and the mesh was exported from blender already.
