### ISSUE TITLE
Phanon MacR.I.P.P. Theta Tier upgrade

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/Acquistion-of-Technology#15]
# Description
The old Phanon MacR.I.P.P. should be upgradeable into theta tier with new visuals of course.

## TODO

- [ ] Create new Theta MacR.I.P.P. mesh
- [ ] Texture the mesh.
- [ ] Finish the mesh in Blender and animate it.
- [ ] Add the new Planet Type to the game.
  - [ ] Create Planet background art.
  - [ ] Create planet selection sounds.
  - [ ] Create new districts art.

**Comment by Fragjacker** [comment]
This is currently in the prototyping phase for the mesh itself.
