### ISSUE TITLE
Warbarge Theta Tier

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/Acquistion-of-Technology#16]
# Description
The Warbarge needs a proper texture and VFX addition for the Theta tier variant of it.

## TODO

- [ ] Create a texture variant of it, using the theta tier aesthetics.
- [ ] Create a new purple particle effect for the thrusters and energy core.
- [ ] Make technology icons for it.
- [ ] Implement the actual technology code for it.
