### ISSUE TITLE
Enigmatic Fortress Theta Tier

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/Acquistion-of-Technology#17]
# Description
Same treatment for the Engimatic Fortress as for the Warbarge #16 

## TODO

- [ ] Create a new purple energy core particle to be used at the bottom of the fortress.
- [ ] Create the actual shipsize for it with the respective weapon slots.
- [ ] Make technology icons for it.
- [ ] Implement the actual technology code for it.
