### ISSUE TITLE
Create Theta Pylon Star

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/Acquistion-of-Technology#18]
# Description
Create an upgrade to the Phanon Pylon Star, when being upgraded by the new theta star imploder. Relates to #14 .

## TODO

- [x] Change the texture of the existing pylon star to be purple.
- [x] Create a new shader to give that purple energy flow.
- [ ] Add some shader FX on it, similar to neutron stars.
- [x] Create galaxy map star icon.
- [ ] Make a selection sound for it. (Can recycle existing one)
