### ISSUE TITLE
Create Theta Emissary

### ISSUE THREAD

**Issue by Fragjacker** [Fragjacker/Acquistion-of-Technology#19]
# Description
Create icons for the components and the necessary code for it to spawn the Theta buildings

## TODO

- [ ] Create Icons.
- [ ] Create Ship section.
- [ ] Create techs to research those ship sections.
- [ ] Update event code to support theta emissaries.
